caddy:
  image: abiosoft/caddy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
   - './static:/app/static:ro'
   - './Caddyfile:/etc/Caddyfile:ro'
   - './.caddy:/root/.caddy'
  links:
    - app
  env_file:
   - './.env'

app:
  build: .
  expose:
   - "9090"
  restart: always
  working_dir: /app
  entrypoint: bash -c "bundle install --local && exec websocketd --port 9090 --passenv GEM_HOME,BUNDLE_APP_CONFIG,RUBY_MAJOR,RUBYGEMS_VERSION,BUNDLE_BIN,BUNDLE_PATH,RUBY_VERSION,BUNDLER_VERSION,PATH bundle exec ruby /app/chat.rb"
  volumes:
   - './Gemfile:/app/Gemfile:ro'
   - './Gemfile.lock:/app/Gemfile.lock:ro'
   - './chat.rb:/app/chat.rb:ro'

  links:
    - redis

redis:
  image: redis
  restart: always
